Fix NameError: uninitialized constant Rails (NameError) in Rakefile
```
$ be rake -T
rake aborted!
NameError: uninitialized constant Rails (NameError)

Rails.deprecator.warn <<~TEXT
^^^^^
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/railties-8.1.1/lib/rails/tasks/statistics.rake:3:in '<top (required)>'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/Rakefile:17:in 'Kernel#load'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/Rakefile:17:in '<top (required)>'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/rake-13.3.1/exe/rake:27:in '<top (required)>'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in 'Kernel.load'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in 'Bundler::CLI::Exec#kernel_load'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/lib/bundler/cli.rb:451:in 'Bundler::CLI#exec'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor.rb:527:in 'Bundler::Thor.dispatch'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/lib/bundler/cli.rb:34:in 'Bundler::CLI.dispatch'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/lib/bundler/cli.rb:28:in 'Bundler::CLI.start'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/exe/bundle:28:in 'block in <top (required)>'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/vendor/bundle/ruby/3.4.0/gems/bundler-2.5.3/exe/bundle:20:in '<top (required)>'
/Users/sue445/.rbenv/versions/3.4.7/bin/bundle:25:in 'Kernel#load'
/Users/sue445/.rbenv/versions/3.4.7/bin/bundle:25:in '<main>'
(See full trace by running task with --trace)
```