Fixed. Coveralls encountered an exception
```
Coveralls encountered an exception:
NoMethodError
undefined method `coverage' for #<SimpleCov::SourceFile:0x00007f909bea4100>
Did you mean?  coverage_data
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/gemfiles/vendor/bundle/ruby/2.7.0/gems/coveralls-0.7.1/lib/coveralls/simplecov.rb:50:in `block in format'
/Users/sue445/.rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `each'
/Users/sue445/.rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `each'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/gemfiles/vendor/bundle/ruby/2.7.0/gems/coveralls-0.7.1/lib/coveralls/simplecov.rb:40:in `format'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/gemfiles/vendor/bundle/ruby/2.7.0/gems/simplecov-0.20.0/lib/simplecov/result.rb:51:in `format!'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/gemfiles/vendor/bundle/ruby/2.7.0/gems/simplecov-0.20.0/lib/simplecov/configuration.rb:197:in `block in at_exit'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/gemfiles/vendor/bundle/ruby/2.7.0/gems/simplecov-0.20.0/lib/simplecov.rb:191:in `run_exit_tasks!'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/gemfiles/vendor/bundle/ruby/2.7.0/gems/simplecov-0.20.0/lib/simplecov.rb:181:in `at_exit_behavior'
/Users/sue445/workspace/github.com/sue445/chatwork_webhook_verify/gemfiles/vendor/bundle/ruby/2.7.0/gems/simplecov-0.20.0/lib/simplecov/defaults.rb:30:in `block in <top (required)>'
```